apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: app
spec:
  secretName: app
  issuerRef:
    name: production-app
    kind: ClusterIssuer
  commonName: thanks.anishbista.xyz
  dnsNames:
  - thanks.anishbista.xya
